declare const __WILL_REPLACE_AMAP_SECURITY_KEY: string;
declare const __WILL_REPLACE_SERVER3_SEND_KEY: string;
declare const __WILL_REPLACE_ENVIRONMENT: string;

export const env = {
  AMAP_SECURITY_KEY: __WILL_REPLACE_AMAP_SECURITY_KEY,
  SERVER3_SEND_KEY: __WILL_REPLACE_SERVER3_SEND_KEY,
  ENVIRONMENT: __WILL_REPLACE_ENVIRONMENT,
}
